apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-express
  name: mongo-express-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 30000
  selector:
    app: mongo-express
  
